openapi: 3.1.0
info:
  version: 1.0.0
  title: Aquatrack app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Aquatrack app
tags:
  - name: Water
    description: Operations about water.
  - name: Auth
    description: Auth operations.
servers:
  # - url: http://localhost:5051
  - url: http://127.0.0.1:5051
  # - url: https://example.com/api/v1
paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
